apiVersion: v1
kind: Pod
metadata:
  name: webserver-1
  labels:
    app: webserver
spec:
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf
        items:
          - key: default.conf
            path: default.conf
  containers:
    - name: webserver
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf
          readOnly: true
    - name: adapter
      image: nginx/nginx-prometheus-exporter:0.4.2
      args: ["-nginx.scrape-uri","http://localhost/nginx_status"]
      ports:
        - containerPort: 9113




  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nginx-conf
  data:
    default.conf: |
      server {
        listen       80;
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
        location /nginx_status {
          stub_status;
          allow 127.0.0.1;  #only allow requests from localhost
          deny all;   #deny all other hosts
        }
      }

