apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksdeployments
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: phpapp
        image: nginx

