apiVersion: v1
kind: Pod 
metadata:
  name: nginx-webserver
spec:
  containers:
  - image: nginx
    name: demo-container1
  - image: busybox
    name: demo-container2
    command:
    - sleep 
    - "3600"
    